### ISSUE TITLE
Socket Error uncaught exception when trying to consume messages

### ISSUE THREAD

**Issue by jeremymills** [prolic/HumusAmqpModule#35]
https://github.com/prolic/HumusAmqpModule/blob/master/src/HumusAmqpModule/Consumer.php#L271

```sh
======================================================================
   The application has thrown an exception!
======================================================================
 AMQPException
 Library error: a socket error occurred
----------------------------------------------------------------------
/usr/lib/composer/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php:271
#0 /usr/lib/composer/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php(271): AMQPQueue->get()
   /usr/lib/composer/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Controller/ConsumerController.php(87): HumusAmqpModule\Consumer->consume(0)
#2 /usr/lib/composer/vendor/zendframework/zend-mvc/src/DispatchListener.php(114): HumusAmqpModule\Controller\ConsumerController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#3 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /usr/lib/composer/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /usr/lib/composer/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /usr/lib/composer/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#7 /var/www/public/index.php(21): Zend\Mvc\Application->run()
#8 {main}
======================================================================
```

Wondering if anything what could be causing this exception and if it should be encapsulated within a try/catch

**Comment by prolic** [comment]
Wrong credentials perhaps?
Am 06.05.2016 23:19 schrieb "Jeremy Mills" <notifications@github.com>:

**Comment by jeremymills** [comment]
@prolic thanks for the quick reply, I guess I should give some more light into the issue..

I run my consumer and it's connected to rabbitmq, it consumes messages with no problems... it's just sometimes after varying times (20 hours or 2 days or even 30 min) it crashes with this exception. I thought it could be the credentials as well, but why would be consuming messages with no problems and then all of a sudden get this exception?

**Comment by prolic** [comment]
Try to update to ext amqp 1.7, this solved a lot of problemls on my side
Am 09.05.2016 22:19 schrieb "Jeremy Mills" <notifications@github.com>:

**Comment by jeremymills** [comment]
Interesting, I will try that and let you know!

**Comment by jeremymills** [comment]
seems to have solved it thanks @prolic!
